name: MedievalRoleplayEngine
version: "1.4.2.1"
author: DanTheTechMan
main: rpsystem.Main
api-version: "1.13"

commands:
  card:
  bird:
  local:
  rp:
  global:
  ooc:
  emote:
  me:
  roll:
  dice:
  title: